import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const inter = Poppins({
  variable: "inter",
  subsets: ["latin"],
  weight:'600',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
